return {
  { import = "lazyvim.plugins.extras.lang.typescript" }, -- Typescript language support
  { import = "lazyvim.plugins.extras.lang.json" }, -- JSON language support
  { import = "lazyvim.plugins.extras.ui.mini-animate" }, -- Animations on certain actions
  { import = "lazyvim.plugins.extras.linting.eslint" }, -- Eslint linting support
  { import = "lazyvim.plugins.extras.formatting.prettier" }, -- Prettier formatting support
  -- { import = "lazyvim.plugins.extras.editor.navic" }, -- Navic
  { import = "lazyvim.plugins.extras.lsp.none-ls" }, -- None-ls Formatting
  -- { import = "lazyvim.plugins.extras.dap.core" }, -- DAP core support
  -- { import = "lazyvim.plugins.extras.dap.nlua" }, -- DAP Neovim Lua Adapter
  -- { import = "lazyvim.plugins.extras.coding.copilot" }, -- Github Copilot
  -- { import = "lazyvim.plugins.extras.coding.yanky" }, -- Smartyank alternative
  -- { import = "lazyvim.plugins.extras.editor.leap" }, -- Alternative to flash.nvim (depreciated by lazyvim)
  -- { import = "lazyvim.plugins.extras.editor.mini-files" }, -- Alternative to neotree
  -- { import = "lazyvim.plugins.extras.lang.clangd" }, -- C/C++ language support
  -- { import = "lazyvim.plugins.extras.lang.cmake" }, -- Cmake language support
  -- { import = "lazyvim.plugins.extras.lang.docker" }, -- Docker language support
  -- { import = "lazyvim.plugins.extras.lang.elixir" }, -- Elixir language support
  -- { import = "lazyvim.plugins.extras.lang.go" }, -- Go language support
  -- { import = "lazyvim.plugins.extras.lang.java" }, -- Java language support
  -- { import = "lazyvim.plugins.extras.lang.python-semshi" }, -- Python (semshi) language support
  -- { import = "lazyvim.plugins.extras.lang.python" }, -- Python language support
  -- { import = "lazyvim.plugins.extras.lang.ruby" }, -- Ruby language support
  -- { import = "lazyvim.plugins.extras.lang.rust" }, -- Rust language support
  -- { import = "lazyvim.plugins.extras.lang.tailwind" }, -- Tailwind (css) language support
  -- { import = "lazyvim.plugins.extras.lang.terraform" }, -- Terraform language support
  -- { import = "lazyvim.plugins.extras.lang.tex" }, -- Tex language support
  -- { import = "lazyvim.plugins.extras.lang.yaml" }, -- YAML language support
  -- { import = "lazyvim.plugins.extras.test.core" }, -- Testing support - Requires additional configuration
  -- { import = "lazyvim.plugins.extras.ui.edgy" }, -- Fancier windows
  -- { import = "lazyvim.plugins.extras.ui.mini-starter" }, -- Alpha replacement
  -- { import = "lazyvim.plugins.extras.util.mini-hipatterns" }, -- Highlight text matching regex (tailwind support included)
  -- { import = "lazyvim.plugins.extras.util.project" }, -- Project management with ahmedkhalf/project.nvim
}
